### ISSUE TITLE
PCF control class: URL

### ISSUE THREAD

**Issue by ewingjm** [ewingjm/power-playwright#19]
# PCF control class: URL

Support is to be added for controls of the _URL_ PCF control class.

## Tasks

- [x] Interface for PCF control class
- [x] Interface(s) for PCF controls
- [x] Class(es) for PCF control strategies
- [x] Class for PCF control class redirector
- [x] Automated unit tests
- [x] Automated integration tests

## Scope

- Get value
- Set value

**Comment by markcunninghamuk** [comment]
@ewingjm can you see any gaps left on this one? or can we close now?
