### ISSUE TITLE
Platform control: Site map

### ISSUE THREAD

**Issue by ewingjm** [ewingjm/power-playwright#22]
# Platform control: Site map

Support is to be added for the _Site map_ platform control.

## Tasks

- [ ] Interface for platform control
- [ ] Class(es) for platform control strategies
- [ ] Automated unit tests
- [ ] Automated integration tests

## Scope

- Open a page
