### ISSUE TITLE
Page: Entity list page

### ISSUE THREAD

**Issue by ewingjm** [ewingjm/power-playwright#24]
# Page: Entity list page

Support is to be added for the _Entity list_ page.

## Tasks

- [ ] Interface for page
- [ ] Class for page
- [ ] Automated unit tests
- [ ] Automated integration tests

## Scope

- Grid control
- Site map control
- Command bar control
