### ISSUE TITLE
Page: Entity record page

### ISSUE THREAD

**Issue by ewingjm** [ewingjm/power-playwright#25]
# Page: Entity record page

Support is to be added for the _Entity record_ page.

## Tasks

- [ ] Interface for page
- [ ] Class for page
- [ ] Automated unit tests
- [ ] Automated integration tests

## Scope

- Form control
- Site map control
- Command bar control
