### ISSUE TITLE
Page: Login page

### ISSUE THREAD

**Issue by ewingjm** [ewingjm/power-playwright#26]
# Page: Login page

Support is to be added for the _Login_ page.

## Tasks

- [x] Interface for page
- [x] Class for page
- [x] Automated unit tests
- [x] Automated integration tests

## Scope

- Login control
